### Moderator Priority Survey Results
* Used for calculating weights of labels

In [1]:
import pandas as pd
import numpy as np

In [4]:
survey = pd.read_csv('Toxicity Severity (Responses) - Form Responses 2.csv')
# Removed timestamps and email addresses

In [5]:
data = survey.iloc[:, 2:7]
data.head()

A message classified as "toxic" by our model. Rate the level of priority that should be given to it. 1, being low priority, 5 being high priority(a mod must absolutely step in).  \
0                                                  3                                                                                                                                  
1                                                  4                                                                                                                                  
2                                                  2                                                                                                                                  
3                                                  2                                                                                                                                  
4                                                  3                                                                                                                                  

  A message classified as an "obscene" by our model . Rate the level of priority that should be given to it. 1, being low priority, 5 being high priority(a mod must absolutely step in).  \
0                                                  4                                                                                                                                        
1        5 (great concern, should be given priority)                                                                                                                                        
2                                                  4                                                                                                                                        
3                           1 (little to no concern)                                                                                                                                        
4                                                  4                                                                                                                                        

  A message classified as  "threat" by our model . Rate the level of priority that should be given to it. 1, being low priority, 5 being high priority(a mod must absolutely step in).  \
0        5 (great concern, should be given priority)                                                                                                                                     
1                                                  4                                                                                                                                     
2        5 (great concern, should be given priority)                                                                                                                                     
3        5 (great concern, should be given priority)                                                                                                                                     
4        5 (great concern, should be given priority)                                                                                                                                     

  A message classified as  "insult" by our model . Rate the level of priority that should be given to it. 1, being low priority, 5 being high priority(a mod must absolutely step in).  \
0                                                  2                                                                                                                                     
1                                                  2                                                                                                                                     
2                           1 (little to no concern)                                         

In [6]:
data.columns = ['toxic', 'obscene', 'threat', 'insult', 'identity_hate']

In [7]:
data.head()

toxic                                      obscene  \
0     3                                            4   
1     4  5 (great concern, should be given priority)   
2     2                                            4   
3     2                     1 (little to no concern)   
4     3                                            4   

                                        threat                    insult  \
0  5 (great concern, should be given priority)                         2   
1                                            4                         2   
2  5 (great concern, should be given priority)  1 (little to no concern)   
3  5 (great concern, should be given priority)                         4   
4  5 (great concern, should be given priority)  1 (little to no concern)   

                                 identity_hate  
0                                            4  
1                                            4  
2  5 (great concern, should be given priority)  
3  5 (great concern, should be given priority)  
4                                            3

In [8]:
data

toxic                                      obscene  \
0                          3                                            4   
1                          4  5 (great concern, should be given priority)   
2                          2                                            4   
3                          2                     1 (little to no concern)   
4                          3                                            4   
5                          4                                            4   
6   1 (little to no concern)                                            3   
7   1 (little to no concern)                                            3   
8                          3                                            3   
9                          2                                            2   
10                         3                                            4   
11                         3                                            2   
12                         2                                            1   
13                         4                                            2   
14                         4                                            2   
15                         2                                            2   
16                         1                                            1   
17                         3                                            4   
18                         2                                            1   
19                         4                                            2   
20                         5                                            3   
21                         1                                            1   
22                         2                                            4   
23                         4                                            5   
24                         3                                            4   
25                         3                                            3   
26                         2                                            3   
27                         3                                            5   
28                         3                                            3   

                                         threat  \
0   5 (great concern, should be given priority)   
1                                             4   
2   5 (great concern, should be given priority)   
3   5 (great concern, should be given priority)   
4   5 (great concern, should be given priority)   
5   5 (great concern, should be given priority)   
6                                             3   
7                                             4   
8                                             4   
9                                             3   
10                                            5   
11                                            5   
12                                            3   
13                                            5   
14                                            2   
15                                            4   
16                                            5   
17                                            5   
18                                            4   
19                                            3   
20                                            5   
21                                            5   
22                                            5   
23                                            4   
24                                            4   
25                                            4   
26                                            4   
27                                            4   
28                                            3   

                                         insult  \
0                                             2   
1                                             2   
2                      1 (li

In [9]:
data = data.replace('5 (great concern, should be given priority)', '5')
data = data.replace('1 (little to no concern)', '1')

In [10]:
data

toxic obscene threat insult identity_hate
0      3       4      5      2             4
1      4       5      4      2             4
2      2       4      5      1             5
3      2       1      5      4             5
4      3       4      5      1             3
5      4       4      5      3             5
6      1       3      3      2             3
7      1       3      4      2             2
8      3       3      4      5             4
9      2       2      3      2             2
10     3       4      5      2             4
11     3       2      5      4             5
12     2       1      3      5             5
13     4       2      5      3             4
14     4       2      2      4             3
15     2       2      4      4             4
16     1       1      5      5             4
17     3       4      5      2             5
18     2       1      4      3             5
19     4       2      3      1             1
20     5       3      5      5             5
21     1       1      5      3             2
22     2       4      5      1             5
23     4       5      4      2             4
24     3       4      4      3             2
25     3       3      4      2             2
26     2       3      4      1             5
27     3       5      4      1             4
28     3       3      3      2             4

In [11]:
data = data.astype('int32')

In [12]:
data.head()

toxic  obscene  threat  insult  identity_hate
0      3        4       5       2              4
1      4        5       4       2              4
2      2        4       5       1              5
3      2        1       5       4              5
4      3        4       5       1              3

In [13]:
data['toxic'][0]

3

### Get the percentage for each label

In [14]:
percent_data = pd.DataFrame()

In [15]:
# For the first label 'toxic'
toxic_1 = len(data['toxic'][data['toxic'] == 1]) / len(data)
toxic_2 = len(data['toxic'][data['toxic'] == 2]) / len(data)
toxic_3 = len(data['toxic'][data['toxic'] == 3]) / len(data)
toxic_4 = len(data['toxic'][data['toxic'] == 4]) / len(data)
toxic_5 = len(data['toxic'][data['toxic'] == 5]) / len(data)

toxic_arr = np.array([toxic_1, toxic_2, toxic_3, toxic_4, toxic_5])
toxic_arr

array([0.13793103, 0.27586207, 0.34482759, 0.20689655, 0.03448276])

In [16]:
# For the second label 'obscene'
obscene_1 = len(data['obscene'][data['obscene'] == 1]) / len(data)
obscene_2 = len(data['obscene'][data['obscene'] == 2]) / len(data)
obscene_3 = len(data['obscene'][data['obscene'] == 3]) / len(data)
obscene_4 = len(data['obscene'][data['obscene'] == 4]) / len(data)
obscene_5 = len(data['obscene'][data['obscene'] == 5]) / len(data)

obscene_arr = np.array([obscene_1, obscene_2, obscene_3, obscene_4, obscene_5])
obscene_arr

array([0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.10344828])

In [17]:
# For the third label 'threat'
threat_1 = len(data['threat'][data['threat'] == 1]) / len(data)
threat_2 = len(data['threat'][data['threat'] == 2]) / len(data)
threat_3 = len(data['threat'][data['threat'] == 3]) / len(data)
threat_4 = len(data['threat'][data['threat'] == 4]) / len(data)
threat_5 = len(data['threat'][data['threat'] == 5]) / len(data)

threat_arr = np.array([threat_1, threat_2, threat_3, threat_4, threat_5])
threat_arr

array([0.        , 0.03448276, 0.17241379, 0.34482759, 0.44827586])

In [18]:
# For the fourth label 'insult'
insult_1 = len(data['insult'][data['insult'] == 1]) / len(data)
insult_2 = len(data['insult'][data['insult'] == 2]) / len(data)
insult_3 = len(data['insult'][data['insult'] == 3]) / len(data)
insult_4 = len(data['insult'][data['insult'] == 4]) / len(data)
insult_5 = len(data['insult'][data['insult'] == 5]) / len(data)

insult_arr = np.array([insult_1, insult_2, insult_3, insult_4, insult_5])
insult_arr

array([0.20689655, 0.34482759, 0.17241379, 0.13793103, 0.13793103])

In [19]:
# For the fifth label 'identity_hate'
identity_hate_1 = len(data['identity_hate'][data['identity_hate'] == 1]) / len(data)
identity_hate_2 = len(data['identity_hate'][data['identity_hate'] == 2]) / len(data)
identity_hate_3 = len(data['identity_hate'][data['identity_hate'] == 3]) / len(data)
identity_hate_4 = len(data['identity_hate'][data['identity_hate'] == 4]) / len(data)
identity_hate_5 = len(data['identity_hate'][data['identity_hate'] == 5]) / len(data)

identity_hate_arr = np.array([identity_hate_1, identity_hate_2, identity_hate_3, identity_hate_4, identity_hate_5])
identity_hate_arr

array([0.03448276, 0.17241379, 0.10344828, 0.34482759, 0.34482759])

In [20]:
percent_data['Toxic Percentage'] = toxic_arr
percent_data['Obscene Percentage'] = obscene_arr
percent_data['Threat Percentage'] = threat_arr
percent_data['Insult Percentage'] = insult_arr
percent_data['Identity_Hate Percentage'] = identity_hate_arr

In [21]:
percent_data = percent_data.rename({0:1, 1:2, 2:3, 3:4, 4:5}, axis='index')

In [22]:
percent_data

Toxic Percentage  Obscene Percentage  Threat Percentage  Insult Percentage  \
1          0.137931            0.172414           0.000000           0.206897   
2          0.275862            0.206897           0.034483           0.344828   
3          0.344828            0.241379           0.172414           0.172414   
4          0.206897            0.275862           0.344828           0.137931   
5          0.034483            0.103448           0.448276           0.137931   

   Identity_Hate Percentage  
1                  0.034483  
2                  0.172414  
3                  0.103448  
4                  0.344828  
5                  0.344828

In [23]:
percent_data.to_csv('percent_data.csv')